### PR TITLE
Add python36 and python38 flavours.

### PR DESCRIPTION
**Pull request by mcepl**
https://build.opensuse.org/request/show/843212#comment-1336525

@bnavigator What do you think?

### CODE REVIEW

**Comment by bnavigator** [comment]
Yes that is the missing piece. You have to decide: Do you want to 

- A. follow through with it and get all the changes of sr#843212 in one piece, or do you want to 
- B. defer the activation of the flavors later. 

For A, I can imagine more packages in Staging:N will fail and it will take some time to sort everything out (see also https://trello.com/c/hrSxAWjp/17-python3-coinstall#comment-5f8ea4fc3b00223378efcb6a). Until then, #60 and so on won't land in Factory.

For B, @DimStar77 or another staging maintainer will need to revert the prjconf definition in Staging:N. https://build.opensuse.org/project/show/home:bnavigator:branches:devel:languages:python:Factory is a plain fork of d:l:p:n:F without the new prjconf. The lua error does not occur there.

**Comment by mcepl** [comment]
Without A we are not really testing these changes, and yes I keep flavours just to python36 and python38, which both **should** be tested and well-working. python39 will be added only later. And yes, of course, I expect some (few … the famous last words) packages to be broken in :N.

**Comment by bnavigator** [comment]
Your original patch also had the `BUILDSET` changed to `python2 python36 python38`.

**Comment by bnavigator** [comment]
Some dumb questions, I am sure you have thought about this but I don't see anything in the macros:

This may eventually build fully for Staging:N. But when it goes into the Tumbleweed repository, what will happen for users? Won't all python3-foo packages cease to exist? Don't we need the python3?-foo packages have a `Provides:` and `Obsoletes:`, for distribution updates to work? And as a result of that, will the python36-foo and python38-foo create numerous "have choice" unresolvables in the openSUSE Build System ad yast/zypper?

**Pull request merged**
