### PR TITLE
Pass `--ignore-installed` to `pip install` in %pyproject_install

### PR DESCRIPTION
**Pull request by manueljacob**
See commit message and https://bugzilla.opensuse.org/show_bug.cgi?id=1201041.

### CODE REVIEW

**Comment by manueljacob** [comment]
I’m working on it right now, I’m not very familiar with `osc` and just succeeded running the source service to grab the revision from my fork. :)

**Comment by bnavigator** [comment]
> running the source service to grab the revision from my fork

You can do that or just apply https://github.com/openSUSE/python-rpm-macros/pull/129.patch in the specfile.

**Comment by manueljacob** [comment]
It seems to work now on Leap: https://build.opensuse.org/package/show/home:mjacob:pyproject_install-ignore-installed/python-python-docs-theme

For the Tumbleweed build I seem to need to branch some projects (python2-wheel, python38, python39) into the test project. They build in the moment. Is there a way to grab all needed packages automatically from devel:languages:python or otherwise speed this up?

Is it somehow possible to trigger [the service](https://build.opensuse.org/package/view_file/devel:languages:python:Factory/python-rpm-macros/_service?expand=1) on the server? For me, it failed because files were not found (possible because they were prefixed with `_service:`). (I managed to do it locally, would it would be interesting to know.)

**Comment by bnavigator** [comment]
> For the Tumbleweed build I seem to need to branch some projects  ...

Adjust your https://build.opensuse.org/projects/home:mjacob:pyproject_install-ignore-installed/meta to not pull in from d:l:p:Factory but from d:l:p/openSUSE_Tumbleweed or openSUSE:Factory/standard instead

> Is it somehow possible to trigger ...

You could change the `mode` parameter. But running it locally with `osc service runall` and then checking in the new source file from hand is the correct way to do it. Packages in Factory must have mode="disabled".

**Comment by manueljacob** [comment]
Success :) https://build.opensuse.org/package/show/home:mjacob:pyproject_install-ignore-installed/python-python-docs-theme

**Comment by mcepl** [comment]
See https://bugzilla.suse.com/show_bug.cgi?id=1201041#c4

Let's keep this as a possible plan B for now.

**Pull request merged**
