### PR TITLE
python_expand $python to basename only

### PR DESCRIPTION
**Pull request by bnavigator**
Avoids fixes like https://build.opensuse.org/request/show/853336?notification_id=24194305#comment-1369915 and more occasions of the same sort (https://github.com/openSUSE/python-rpm-macros/issues/66#issuecomment-731785692)

### CODE REVIEW

**Comment by mcepl** [comment]
Yes, that’s probably the best idea.

**Comment by bnavigator** [comment]
I updated the README

**Comment by mcepl** [comment]
THank you.

**Comment by bnavigator** [comment]
There is another commit after you already merged. If you want to consider picking that one: e0e39fa

**Pull request merged**
