### PR TITLE
Compile and fix_shebang in %python_install macros

### PR DESCRIPTION
**Pull request by danigm**

### CODE REVIEW

**Review by mcepl — APPROVED** [review]
Agree, but it will need thorough testing and wait before I will be persuaded it doesn’t cause some damage.

**Comment by mcepl** [comment]
Please, update the package.

**Comment by bnavigator** [comment]
See https://github.com/openSUSE/python-rpm-macros/pull/155#issue-1590432429.

This will break all packages using something like

```
%python_install --myargs
```

**Comment by bnavigator** [comment]
Reverted in https://github.com/openSUSE/python-rpm-macros/commit/0a1f0d9a0d295f1414c7bde6a6f0ef344ff0b37d

**Comment by danigm** [comment]
Good catch, I didn't notice about that problem. @bnavigator, @mcepl what do you think about this version with support for arguments? https://github.com/openSUSE/python-rpm-macros/pull/164

**Pull request merged**
