### PR TITLE
Fix macros for usage with RPM 4.14

### PR DESCRIPTION
**Pull request by DimStar77**
RPM 4.14 became much stricter in validating options in macros...

### CODE REVIEW

**Comment by scarabeusiv** [comment]
Makes sense, tho I dunno if matejcik has it based on service run so point me somewhere over irc :)

**Comment by matejcik** [comment]
you need to run a .sh in the package

**Comment by DimStar77** [comment]
https://build.opensuse.org/project/monitor/home:dimstar:Factory (Staging_A): most issues seem go be gone now, but python-tox fails - so still not ready

**Comment by DimStar77** [comment]
python-tox was actually broken before (from openSUSE:Factory/standard):

```
[   24s] + make html
[   24s] sphinx-build -b html -d _build/doctrees   . _build/html
[   25s] Running Sphinx v1.6.5
[   25s] making output directory...
[   25s] 
[   25s] Exception occurred:
[   25s]   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
[   25s]     raise DistributionNotFound(req, requirers)
[   25s] pkg_resources.DistributionNotFound: The 'tox' distribution was not found and is required by the application
[   25s] The full traceback has been saved in /tmp/sphinx-err-i8u290py.log, if you want to report the issue to the developers.
[   25s] Please also report this if it was a user error, so that a better error message can be provided next time.
[   25s] A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
[   25s] make: *** [Makefile:40: html] Error 1
```

The difference here being that RPM 4.14 raises this error (as one would expect) and old rpm versions 'missed it'

**Pull request merged**
